name: dnora
channels:
  - conda-forge
dependencies:
  - python=>3.9
  - matplotlib>=3.1
  - numpy>=1.17
  - scipy>=1.7
  - netcdf4
  - pandas
  - xarray=>0.20.1
  - meshio
  - pip
  - utm
  - dask
  
  

